import "./globals.css";
import RootStyleRegistry from "@/app/emotion";
import { HeaderSimple } from "@/app/headerSimple";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const headers = [
    { link: "/", label: "Prices" },
    { link: "/submit", label: "Submit" },
    { link: "/about", label: "About" },
  ];

  return (
    <html lang="en">
      <body>
        <RootStyleRegistry>
          <HeaderSimple links={headers} />
          <main className="min-h-screen bg-background flex flex-col items-center">
            {children}
          </main>
        </RootStyleRegistry>
      </body>
    </html>
  );
}
